services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\MfaFrontend\:
    resource: '../Classes/*'

  Causal\MfaFrontend\Backend\Form\FormDataProvider\TotpEditRow:
    public: true

  Causal\MfaFrontend\Hook\DataHandler:
    public: true

  Causal\MfaFrontend\Handler\TotpSetupHandler:
    public: true
